# Generated by Django 6.0.2 on 2026-02-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='entry_title',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
